SITE_NAME: My Blog
AUTHOR_NAME: Me

MODULES:
  page:
    active: true
  blog:
    active: true
  archive:
    active: true
  tags:
    active: true
  pygments:
    active: true
    style: tango

NAVIGATION:
  - route: blog.index
    label: blog
  - route: archive.index
    label: archive
  - route: page.show
    label: about
    file_path: about